[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
    "asgiref==3.11.0",
    "celery>=5.6.2",
    "django==6.0.1",
    "django-cors-headers==4.9.0",
    "djangorestframework==3.16.1",
    "djangorestframework-simplejwt==5.5.1",
    "dotenv==0.9.9",
    "flower>=2.0.1",
    "groq>=1.1.2",
    "gunicorn>=25.1.0",
    "ipykernel>=7.2.0",
    "joblib>=1.5.3",
    "numpy>=2.4.3",
    "optuna>=4.8.0",
    "paddleocr==3.4.0",
    "paddlepaddle==3.0.0rc1",
    "pandas>=3.0.1",
    "pdfplumber>=0.11.9",
    "pillow>=12.1.0",
    "pipeline>=0.1.0",
    "psycopg2-binary==2.9.11",
    "pyjwt==2.11.0",
    "python-dotenv==1.2.1",
    "redis>=7.3.0",
    "scikit-learn>=1.8.0",
    "sqlparse==0.5.5",
    "tqdm>=4.67.3",
    "tzdata==2025.3 ; sys_platform == 'win32'",
    "xgboost>=3.2.0",
]
