# Generated by Django 6.0.1 on 2026-03-08 06:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assignsubject',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.teacher'),
        ),
        migrations.AddField(
            model_name='grade',
            name='class_teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignsubject',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.grade'),
        ),
        migrations.AddField(
            model_name='grade',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='subject',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='assignsubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.subject'),
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('name', 'section', 'academic_year', 'organization')},
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('name', 'organization')},
        ),
        migrations.AlterUniqueTogether(
            name='assignsubject',
            unique_together={('subject', 'grade')},
        ),
    ]
