# Generated by Django 6.0.1 on 2026-03-15 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='calendar_type',
            field=models.CharField(choices=[('AD', 'Gregorian (AD)'), ('BS', 'Bikram Sambat (BS)')], default='AD', max_length=2),
        ),
    ]
