# Generated by Django 6.0.1 on 2026-03-15 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_organization_calendar_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='calendar_type',
        ),
    ]
