# Generated by Django 6.0.1 on 2026-03-20 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_quizattempt_studentresponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizattempt',
            name='status',
            field=models.CharField(choices=[('in-progress', 'In Progress'), ('completed', 'Completed'), ('auto-submitted', 'Auto Submitted'), ('missed', 'Missed')], default='in-progress', max_length=20),
        ),
    ]
