# Generated by Django 6.0.1 on 2026-03-12 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
        ('organizations', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourcefolder',
            name='subject',
        ),
        migrations.AddField(
            model_name='resourcefolder',
            name='sub_assign',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='organizations.assignsubject'),
            preserve_default=False,
        ),
    ]
