# Generated by Django 6.0.1 on 2026-03-14 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_flashcarddeck_flashcard'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flashcarddeck',
            options={'verbose_name_plural': 'Flashcard Decks'},
        ),
    ]
