# Generated by Django 6.0.1 on 2026-03-14 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_alter_flashcarddeck_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='back_image',
            field=models.ImageField(blank=True, null=True, upload_to='flashcards/back/'),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='front_image',
            field=models.ImageField(blank=True, null=True, upload_to='flashcards/front/'),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='back',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='front',
            field=models.TextField(blank=True, null=True),
        ),
    ]
