# Generated by Django 6.0.1 on 2026-03-18 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0008_quizresult_studentanswer'),
        ('organizations', '0004_remove_organization_calendar_type'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Remark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remarks_created', to='users.teacher')),
                ('sub_assign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remarks', to='organizations.assignsubject')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
