# Generated by Django 6.0.1 on 2026-03-19 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0009_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published')], default='DRAFT', max_length=10),
        ),
    ]
