# Generated by Django 6.0.1 on 2026-03-19 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0010_quiz_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='status',
        ),
    ]
