# Generated by Django 6.0.1 on 2026-03-19 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0013_teacherquizremark'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeacherQuizRemark',
        ),
    ]
