# Generated by Django 6.0.1 on 2026-03-19 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0014_delete_teacherquizremark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentresponse',
            name='attempt',
        ),
        migrations.RemoveField(
            model_name='remark',
            name='createdBy',
        ),
        migrations.RemoveField(
            model_name='remark',
            name='sub_assign',
        ),
        migrations.RemoveField(
            model_name='studentresponse',
            name='question',
        ),
        migrations.RemoveField(
            model_name='studentresponse',
            name='selected_choice',
        ),
        migrations.DeleteModel(
            name='QuizAttempt',
        ),
        migrations.DeleteModel(
            name='Remark',
        ),
        migrations.DeleteModel(
            name='StudentResponse',
        ),
    ]
