# Generated by Django 6.0.1 on 2026-03-28 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0016_resource_extracted_text_resource_processing_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcarddeck',
            name='is_ai_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quiz',
            name='is_ai_generated',
            field=models.BooleanField(default=False),
        ),
    ]
