# Generated by Django 6.0.1 on 2026-04-06 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0017_flashcarddeck_is_ai_generated_quiz_is_ai_generated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='topic_tag',
        ),
    ]
