# Generated by Django 6.0.1 on 2026-04-06 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0018_remove_quiz_topic_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='description',
        ),
    ]
