# Generated by Django 6.0.1 on 2026-04-06 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0019_remove_quiz_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='processing_status',
        ),
    ]
