# Generated by Django 6.0.1 on 2026-04-10 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0020_remove_resource_processing_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='default_points_per_question',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
