# Generated by Django 6.0.1 on 2026-04-11 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0021_quiz_default_points_per_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='points_override',
            field=models.PositiveIntegerField(blank=True, help_text='Overrides quiz default points', null=True),
        ),
    ]
