# Generated by Django 6.0.1 on 2026-04-19 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0022_alter_question_points_override'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='end_datetime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='start_datetime',
            field=models.DateTimeField(),
        ),
    ]
